#!/bin/sh

set -e

source ./common

# Create a Kubernetes cluster
gcloud beta container clusters create \
  --enable-autoscaling \
  --min-nodes 1 \
  --max-nodes 5 \
  $CLUSTER_NAME

# Fetch its credentials so we can use kubectl locally
gcloud container clusters get-credentials $CLUSTER_NAME

# Create a GCS bucket for data storage
gsutil mb gs://$BUCKET_NAME

# Make a service account for our containers
gcloud iam service-accounts create $SERVICE_ACCOUNT

# Grant it read/write permissions on our bucket
gsutil acl ch -u ${SERVICE_ACCOUNT_EMAIL}:W gs://$BUCKET_NAME

# Get keys for the service account
gcloud iam service-accounts keys create \
  ${SERVICE_ACCOUNT}-key.json \
  --iam-account $SERVICE_ACCOUNT_EMAIL

# Import the credentials into the cluster as a secret
kubectl create secret generic ${SERVICE_ACCOUNT}-creds --from-file=service-account.json=${SERVICE_ACCOUNT}-key.json

# Now, launch our workers onto the cluster
kubectl create -f trainer.yaml
kubectl create -f player.yaml
